# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Greyproxy < Formula
  desc "SOCKS5 proxy with DNS resolution and web dashboard for network sandboxing"
  homepage "https://github.com/GreyhavenHQ/greyproxy"
  version "0.2.7"
  license "Apache-2.0"

  depends_on "terminal-notifier" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GreyhavenHQ/greyproxy/releases/download/v0.2.7/greyproxy_0.2.7_darwin_amd64.tar.gz"
      sha256 "4d5758678e4f9bee6e943e8be539bd1b6af3ef47213588b627ee5d02fb3c9196"

      define_method(:install) do
        bin.install "greyproxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GreyhavenHQ/greyproxy/releases/download/v0.2.7/greyproxy_0.2.7_darwin_arm64.tar.gz"
      sha256 "83ed972786a296618c40bba357183326ca967a4412678564ffe9435b69f36e1f"

      define_method(:install) do
        bin.install "greyproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GreyhavenHQ/greyproxy/releases/download/v0.2.7/greyproxy_0.2.7_linux_amd64.tar.gz"
      sha256 "31fd87b3202a734bad6db665065e03b2ca56a570d14acabb1b28e6cd94a3b911"
      define_method(:install) do
        bin.install "greyproxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GreyhavenHQ/greyproxy/releases/download/v0.2.7/greyproxy_0.2.7_linux_arm64.tar.gz"
      sha256 "182c8259f1c59ffd99e9ef99ea97e3836f54897b0f990ffdf92bc3c7dcd45124"
      define_method(:install) do
        bin.install "greyproxy"
      end
    end
  end

  def caveats
    <<~EOS
      For desktop notifications on macOS, install terminal-notifier:
        brew install terminal-notifier
    EOS
  end

  test do
    system bin/"greyproxy", "-V"
  end
end
