# This file was generated by GoReleaser. DO NOT EDIT.
cask "greywall" do
  name "greywall"
  desc "Sandboxed command execution with network isolation"
  homepage "https://github.com/GreyhavenHQ/greywall"
  version "0.2.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "greywall"
  depends_on cask: [
      "greyproxy",
    ]

  on_macos do
    on_intel do
      url "https://github.com/GreyhavenHQ/greywall/releases/download/v#{version}/greywall_#{version}_Darwin_x86_64.tar.gz"
      sha256 "07aef7328bb29306f396956d7494c39ededc7246532a0ecf67ecd1f9c8045361"
    end
    on_arm do
      url "https://github.com/GreyhavenHQ/greywall/releases/download/v#{version}/greywall_#{version}_Darwin_arm64.tar.gz"
      sha256 "9e6dbdf7ab76d3eb6b3a213bc79dd8a42cfab8fbacc7be5b813c949ba7d990a7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/GreyhavenHQ/greywall/releases/download/v#{version}/greywall_#{version}_Linux_x86_64.tar.gz"
      sha256 "5c685a21a40305d5344e44e43274e5790a8bb7af68d853ee0bcf7dae507d5b75"
    end
    on_arm do
      url "https://github.com/GreyhavenHQ/greywall/releases/download/v#{version}/greywall_#{version}_Linux_arm64.tar.gz"
      sha256 "c7114005f7d50b1b389055dea4ada80dd124c6511689d47746dcfd75b523c8f2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/greywall"]
    end
  end

  caveats do
    "greyproxy is installed as a dependency and runs automatically."
    "Dashboard: http://localhost:43080"
  end

  # No zap stanza required
end
