# This file was generated by GoReleaser. DO NOT EDIT.
cask "greywall" do
  name "greywall"
  desc "Sandboxed command execution with network isolation"
  homepage "https://github.com/GreyhavenHQ/greywall"
  version "0.2.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "greywall"
  depends_on cask: [
      "greyproxy",
    ]

  on_macos do
    on_intel do
      url "https://github.com/GreyhavenHQ/greywall/releases/download/v#{version}/greywall_#{version}_Darwin_x86_64.tar.gz"
      sha256 "7efd91779ef7dcb67a8103b670d52cae3b454a5bdba4d87735d112d03f5b1782"
    end
    on_arm do
      url "https://github.com/GreyhavenHQ/greywall/releases/download/v#{version}/greywall_#{version}_Darwin_arm64.tar.gz"
      sha256 "eac074ffcc60377e981f38eaec556cd061079c18cba05e292adcf1ae68d2ad57"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/GreyhavenHQ/greywall/releases/download/v#{version}/greywall_#{version}_Linux_x86_64.tar.gz"
      sha256 "b0d8bd59beca81a9ab787022a6e8ed34e29dc4b038a5773d1afba8431eb42387"
    end
    on_arm do
      url "https://github.com/GreyhavenHQ/greywall/releases/download/v#{version}/greywall_#{version}_Linux_arm64.tar.gz"
      sha256 "d5a092f36cb3c52be5021a7a30a8c48616c52b5604b77e43bb44e38546e5faeb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/greywall"]
    end
  end

  caveats do
    "greyproxy is installed as a dependency and runs automatically."
    "Dashboard: http://localhost:43080"
  end

  # No zap stanza required
end
