# This file was generated by GoReleaser. DO NOT EDIT.
cask "greywall" do
  version "0.3.2"

  on_macos do
    on_intel do
      url "https://github.com/GreyhavenHQ/greywall/releases/download/v#{version}/greywall_#{version}_Darwin_x86_64.tar.gz"
      sha256 "d860cebfd8f024b12b986b9e4701d563da77049f6c89f531a4c7267bbdf7363c"
    end
    on_arm do
      url "https://github.com/GreyhavenHQ/greywall/releases/download/v#{version}/greywall_#{version}_Darwin_arm64.tar.gz"
      sha256 "8bf5926c80c5583d56bbc2aef1f74d6c9b49546bc08b87660172e74444accfa8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/GreyhavenHQ/greywall/releases/download/v#{version}/greywall_#{version}_Linux_x86_64.tar.gz"
      sha256 "f986765222ea6720aa9e8071139410d41e756944abbca2c51f3a5bda6b0d6104"
    end
    on_arm do
      url "https://github.com/GreyhavenHQ/greywall/releases/download/v#{version}/greywall_#{version}_Linux_arm64.tar.gz"
      sha256 "1344c336e4888f434ac2ce07d9fdce32e7c427d78b433f9b1eb7955027d5d3c0"
    end
  end

  name "greywall"
  desc "Sandboxed command execution with network isolation"
  homepage "https://github.com/GreyhavenHQ/greywall"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "greyproxy",
    ]

  binary "greywall"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/greywall"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    greyproxy is installed as a dependency and runs automatically.
    Dashboard: http://localhost:43080
  EOS
end
