# This file was generated by GoReleaser. DO NOT EDIT.
cask "greyproxy" do
  version "0.4.4"

  on_macos do
    on_intel do
      sha256 "fabd83603625e6ecf4911eaa25b961383029ad90a3f3be3f3d2612d307c37ce9"
      url "https://github.com/GreyhavenHQ/greyproxy/releases/download/v#{version}/greyproxy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce84e49bac299d96f205a830dafef45e733fdb8ce0780ece4fc289218d736d1f"
      url "https://github.com/GreyhavenHQ/greyproxy/releases/download/v#{version}/greyproxy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8f90e4cfc02119135b2d302e07a3f3b694b25cfbee15561461f7c14f2c99a053"
      url "https://github.com/GreyhavenHQ/greyproxy/releases/download/v#{version}/greyproxy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6320a4ba38ec41f760a837fa3f55181db542bd619d330011290a32793e0d528e"
      url "https://github.com/GreyhavenHQ/greyproxy/releases/download/v#{version}/greyproxy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "greyproxy"
  desc "SOCKS5 proxy with DNS resolution and web dashboard for network sandboxing"
  homepage "https://github.com/GreyhavenHQ/greyproxy"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "terminal-notifier",
    ]

  binary "greyproxy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/greyproxy"]
      system_command "#{staged_path}/greyproxy", args: ["install", "-f"]
    end
  end

  uninstall_postflight do
    if OS.mac?
      system_command "#{staged_path}/greyproxy", args: ["uninstall", "-f"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    greyproxy has been installed and started as a launchd user agent.
    Dashboard: http://localhost:43080

    For desktop notifications on macOS, install terminal-notifier:
      brew install terminal-notifier
  EOS
end
