# This file was generated by GoReleaser. DO NOT EDIT.
cask "greyproxy" do
  name "greyproxy"
  desc "SOCKS5 proxy with DNS resolution and web dashboard for network sandboxing"
  homepage "https://github.com/GreyhavenHQ/greyproxy"
  version "0.2.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "greyproxy"
  depends_on formula: [
      "terminal-notifier",
    ]

  on_macos do
    on_intel do
      url "https://github.com/GreyhavenHQ/greyproxy/releases/download/v#{version}/greyproxy_#{version}_darwin_amd64.tar.gz"
      sha256 "b0a646d7f6b6710a00cbc7ad5451f1c31e21c4d3cc418cb560808db7cdeea3be"
    end
    on_arm do
      url "https://github.com/GreyhavenHQ/greyproxy/releases/download/v#{version}/greyproxy_#{version}_darwin_arm64.tar.gz"
      sha256 "342edb28638a6df5a2be2e090d1391057be71818c7e121480efce3a24eda6f35"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/GreyhavenHQ/greyproxy/releases/download/v#{version}/greyproxy_#{version}_linux_amd64.tar.gz"
      sha256 "0e8408fab78de16a212182013fd8be23a9fd43f0e4320f7b935b9080d8316146"
    end
    on_arm do
      url "https://github.com/GreyhavenHQ/greyproxy/releases/download/v#{version}/greyproxy_#{version}_linux_arm64.tar.gz"
      sha256 "26152feeeebc677a8fc4d489015621bbff1e8cb9580c1d4dbfa82b694cb86d7d"
    end
  end

  caveats do
    "For desktop notifications on macOS, install terminal-notifier:"
    "  brew install terminal-notifier"
  end

  # No zap stanza required
end
