# This file was generated by GoReleaser. DO NOT EDIT.
cask "greyproxy" do
  version "0.4.3"

  on_macos do
    on_intel do
      sha256 "847a56c9558b78f935b784331ada2db8477ba3545b960d4bef70a36c388389ea"
      url "https://github.com/GreyhavenHQ/greyproxy/releases/download/v#{version}/greyproxy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ebd841488e4a20e6d1770f20c13becf47a1480207d970fa6e78b65fddd7dd082"
      url "https://github.com/GreyhavenHQ/greyproxy/releases/download/v#{version}/greyproxy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a3c4b8bdd0e6582d7378f9e5db354f3e9cae6ada66bcdfc558fa18857d0f999d"
      url "https://github.com/GreyhavenHQ/greyproxy/releases/download/v#{version}/greyproxy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a50fd137496e087922e9ecf11547d1a6c81ce78c046a62d9cb5c8cfe22ea126d"
      url "https://github.com/GreyhavenHQ/greyproxy/releases/download/v#{version}/greyproxy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "greyproxy"
  desc "SOCKS5 proxy with DNS resolution and web dashboard for network sandboxing"
  homepage "https://github.com/GreyhavenHQ/greyproxy"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "terminal-notifier",
    ]

  binary "greyproxy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/greyproxy"]
      system_command "#{staged_path}/greyproxy", args: ["install", "-f"]
    end
  end

  uninstall_postflight do
    if OS.mac?
      system_command "#{staged_path}/greyproxy", args: ["uninstall", "-f"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    greyproxy has been installed and started as a launchd user agent.
    Dashboard: http://localhost:43080

    For desktop notifications on macOS, install terminal-notifier:
      brew install terminal-notifier
  EOS
end
